# Generated by Django 6.0.5 on 2026-10-01 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apriorirun_max_len_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='app_rating_user_id_d94130_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='app_rating_copy_id_c1bec0_idx',
        ),
        migrations.AddField(
            model_name='apriorirun',
            name='books_with_rules_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='apriorirun',
            name='covered_users_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('books_with_rules_count__isnull', True), ('books_with_rules_count__gte', 0), _connector='OR'), name='apriori_books_with_rules_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('covered_users_count__isnull', True), ('covered_users_count__gte', 0), _connector='OR'), name='apriori_covered_users_non_negative'),
        ),
    ]
